[workspace]
authors = ["Kyle Cranmer <kyle.cranmer@nyu.edu>"]
channels = ["conda-forge"]
name = "sbi-tutorial"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks.start]
cmd = "jupyter-lab"

[dependencies]
python = ">=3.13.5,<3.14"
pytorch = ">=2.5.1,<3"
sbi = ">=0.24.0,<0.25"
jupyterlab = ">=4.4.4,<5"
notebook = ">=6.4.12,<7"
ipywidgets = ">=8.1.7,<9"
